### ISSUE TITLE
Only works for single-line content..?

### ISSUE THREAD

**Issue by dylanh724** [ClaudeBot/hubot-paste#2]
I paste multiple lines and only the 1st line gets pastebin'd :(

**Comment by mbwk** [comment]
What an oversight!

I think one way to implement this would be to have two commands: one to begin the paste, and one to end it.  Would probably also need to use brain's persistence to store the paste as it is being built.

**Comment by MrSaints** [comment]
- The behaviour is somewhat [expected](https://github.com/ClaudeBot/hubot-paste/blob/master/src/paste.coffee#L33)
- That is, commands are single-lined with its arguments
- If it were to receive multiple lines, it should still encode it correctly, but on adapters such as IRC (and shell), it would receive multiple lines as separate messages *(this might be the same for all adapters actually, I'm not too sure)*
- I agree. A possible multiple line solution would be to design a command to enable a write buffer and a command to close it off and paste it. It need not use the brain's persistence. It can store the temporary data within its own scope *(I believe)*. Care should be taken to ensure it writes only the author's messages (and maybe throw in a delete last line command?). We are possibly looking into some low-level editor here...

I'll look into it if I get the chance to, otherwise feel free to submit a PR or any other suggestions / advice.

**Comment by MrSaints** [comment]
Sorry for the delay. Better late than never I suppose.

I've applied a fix that seems to be working on the Telegram adapter at least.

I'm not sure if it'll work with IRC (for reasons stated above).

I'll keep this open for a while. Let me know if you have any questions.
